#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  EasyHybrid: Python interface for QM/MM and molecular simulations using pDynamo3
#  Module: Mesh smoothing utilities for isosurface representations
#          (orbital / density / potential / MEP / external-cube surfaces
#          generated by marching cubes -- see surface_analysis_window.py).
#
#  Copyright 2022-2026 Fernando Bachega
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  Description:
#      Taubin Smoothing (Taubin, 1995 -- "A Signal Processing Approach to
#      Fair Surface Design"). A two-pass variant of Laplacian smoothing:
#      each iteration does a "shrink" pass with factor lambda (>0) followed
#      by an "inflate" pass with factor mu (<0, |mu| > lambda). The inflate
#      pass compensates almost exactly for the shrink pass's volume loss,
#      so -- unlike plain Laplacian smoothing, which visibly shrinks a
#      marching-cubes isosurface a little more on every iteration -- an
#      orbital lobe or density blob keeps roughly its original size/volume
#      even after many iterations, while the "staircase"/faceted look from
#      a coarse grid gets smoothed away.
#
#      [SAME DATA-LAYOUT NOTE AS mesh_decimation.pyx] vertices/normals are
#      FLAT 1-D arrays (x0,y0,z0,x1,y1,z1,...), and the mesh coming
#      straight out of surface_parser()/surface_parser_mep() has NO vertex
#      sharing at all (every triangle owns 3 unique vertex slots, 'indexes'
#      is just np.arange(n_slots)) -- so there is no usable adjacency graph
#      to smooth over until coincident slots are welded together first.
#      This module does that welding internally (grouping vertex slots by
#      near-identical position, using a tiny weld_epsilon -- NOT the same
#      thing as mesh_decimation's user-facing cell_size, which is meant to
#      actually simplify the mesh; this one is just meant to recognise
#      "same point, duplicated across triangles"). Works the same way
#      whether called on the raw marching-cubes output OR on an
#      already-decimated (vertex_clustering_decimate) mesh, which already
#      has real shared indices -- either way, the output has the SAME
#      array lengths/layout as the input (same number of vertex slots and
#      triangles), only the positions/normals move; 'colors' and 'indexes'
#      are left for the caller to keep unchanged.
#
import numpy as np
cimport numpy as np
cimport cython

#cython: boundscheck=False
#cython: wraparound=False
#cython: initializedcheck=False
#cython: cdivision=True

from libc.math cimport floor


@cython.boundscheck(False)
@cython.wraparound(False)
cdef _weld_slots(np.ndarray[np.float32_t, ndim=1] vertices, double weld_epsilon):
    """ Agrupa slots de vertice por posicao quase-identica (grade com celula
        'weld_epsilon' -- bem menor que qualquer cell_size de decimacao
        util; serve so' pra reconhecer duplicatas exatas/quase-exatas
        geradas pelo formato "sem compartilhamento" deste codebase, nao pra
        simplificar a malha).

        Returns (slot_weld, n_welds): slot_weld[slot] = weld_id (0..n_welds-1).
    """
    cdef Py_ssize_t n_slots = vertices.shape[0] // 3
    cdef np.ndarray[np.int64_t, ndim=1] slot_weld = np.empty(n_slots, dtype=np.int64)
    cdef dict cell_to_weld = {}
    cdef Py_ssize_t slot, ix, iy, iz, wid
    cdef Py_ssize_t n_welds = 0
    cdef object key

    for slot in range(n_slots):
        ix = <Py_ssize_t> floor(vertices[3 * slot]     / weld_epsilon)
        iy = <Py_ssize_t> floor(vertices[3 * slot + 1] / weld_epsilon)
        iz = <Py_ssize_t> floor(vertices[3 * slot + 2] / weld_epsilon)
        key = (ix, iy, iz)
        if key in cell_to_weld:
            wid = cell_to_weld[key]
        else:
            wid = n_welds
            cell_to_weld[key] = wid
            n_welds += 1
        slot_weld[slot] = wid

    return slot_weld, n_welds


@cython.boundscheck(False)
@cython.wraparound(False)
cpdef tuple taubin_smooth(np.ndarray[np.float32_t, ndim=1] vertices,
                          np.ndarray[np.uint32_t,  ndim=1] indexes,
                          int iterations = 10,
                          double lambda_factor = 0.5,
                          double mu_factor = -0.53,
                          double weld_epsilon = 1e-4):
    """ Taubin (lambda | mu) smoothing.

        Parameters:
            vertices : (3*S,) float32 -- flat vertex positions (S = number
                       of vertex slots, same layout as mesh_decimation.pyx)
            indexes  : (3*T,) uint32  -- flat triangle index list (T
                       triangles); used ONLY to build adjacency (which
                       welded points are connected by an edge), not
                       modified or returned
            iterations : number of lambda+mu double-passes. ~10-20 is
                       usually enough to remove marching-cubes faceting
                       without noticeably softening real surface features;
                       higher values keep smoothing (slowly) with no
                       shrinkage, unlike plain Laplacian.
            lambda_factor : "shrink" pass factor, 0 < lambda < 1 (default
                       0.5, the value used in Taubin's original paper)
            mu_factor : "inflate" pass factor, mu < 0 and abs(mu) slightly
                       larger than lambda_factor (default -0.53) -- this
                       specific asymmetry is what cancels out the shrink
                       pass's volume loss almost exactly; DO NOT set
                       mu = -lambda_factor (that combination still shrinks,
                       just slower -- see Taubin 1995 section 3 for why).
            weld_epsilon : grid cell size used ONLY to recognise duplicate/
                       coincident vertex slots as "the same point" for
                       building the smoothing adjacency graph (see module
                       docstring) -- NOT a simplification parameter. Keep
                       this small (default 1e-4, in the same units as
                       'vertices') relative to the mesh's real feature
                       size; a value this small only merges points that
                       are, for practical purposes, exactly coincident.

        Returns:
            (new_vertices, new_normals) -- same length/layout as the input
            'vertices' (new_normals is freshly recomputed from the smoothed
            geometry, flat (3*S,) float32, one normal per vertex SLOT --
            NOT per weld point, so it can be used as a drop-in replacement
            for the surface's old normals array). 'colors' and 'indexes'
            are unchanged by this function -- the caller keeps its own
            copies of those.
    """
    cdef Py_ssize_t n_slots = vertices.shape[0] // 3
    cdef Py_ssize_t n_indexes = indexes.shape[0]
    cdef Py_ssize_t n_tris = n_indexes // 3

    if iterations <= 0:
        raise ValueError("iterations deve ser positivo (recebido: {})".format(iterations))
    if lambda_factor <= 0.0:
        raise ValueError("lambda_factor deve ser positivo (recebido: {})".format(lambda_factor))
    if mu_factor >= 0.0:
        raise ValueError("mu_factor deve ser negativo (recebido: {})".format(mu_factor))
    if n_slots == 0 or n_tris == 0:
        return (vertices, np.zeros(vertices.shape[0], dtype=np.float32))

    cdef np.ndarray[np.int64_t, ndim=1] slot_weld
    cdef Py_ssize_t n_welds
    slot_weld, n_welds = _weld_slots(vertices, weld_epsilon)

    # --- posicao inicial por weld point (media das posicoes dos slots que
    #     colapsaram nele -- praticamente identicas por construcao) ---
    cdef np.ndarray[np.float64_t, ndim=1] weld_pos = np.zeros(3 * n_welds, dtype=np.float64)
    cdef np.ndarray[np.int64_t, ndim=1] weld_count = np.zeros(n_welds, dtype=np.int64)
    cdef Py_ssize_t slot, wid, i, j

    for slot in range(n_slots):
        wid = slot_weld[slot]
        weld_pos[3 * wid]     += vertices[3 * slot]
        weld_pos[3 * wid + 1] += vertices[3 * slot + 1]
        weld_pos[3 * wid + 2] += vertices[3 * slot + 2]
        weld_count[wid] += 1
    for wid in range(n_welds):
        weld_pos[3 * wid]     /= weld_count[wid]
        weld_pos[3 * wid + 1] /= weld_count[wid]
        weld_pos[3 * wid + 2] /= weld_count[wid]

    # --- grafo de adjacencia entre weld points (arestas dos triangulos) ---
    cdef list adjacency = [set() for _ in range(n_welds)]
    cdef Py_ssize_t a, b, c
    cdef set adj_a, adj_b, adj_c

    for i in range(n_tris):
        a = slot_weld[indexes[3 * i]]
        b = slot_weld[indexes[3 * i + 1]]
        c = slot_weld[indexes[3 * i + 2]]
        if a != b:
            adjacency[a].add(b); adjacency[b].add(a)
        if b != c:
            adjacency[b].add(c); adjacency[c].add(b)
        if a != c:
            adjacency[a].add(c); adjacency[c].add(a)

    # --- iteracoes de Taubin: passada lambda (encolhe) + passada mu
    #     (infla, compensando quase toda a perda de volume da passada
    #     anterior -- ver docstring). Pontos sem vizinhos (weld isolado,
    #     nao deveria acontecer numa malha valida, mas por seguranca) ficam
    #     parados. ---
    cdef np.ndarray[np.float64_t, ndim=1] cur  = weld_pos
    cdef np.ndarray[np.float64_t, ndim=1] nxt  = np.empty_like(weld_pos)
    cdef double avg_x, avg_y, avg_z
    cdef Py_ssize_t deg, it, pass_idx
    cdef double factor
    cdef object neighbor

    for it in range(iterations):
        for pass_idx in range(2):
            factor = lambda_factor if pass_idx == 0 else mu_factor
            for wid in range(n_welds):
                adj_a = adjacency[wid]
                deg = len(adj_a)
                if deg == 0:
                    nxt[3 * wid]     = cur[3 * wid]
                    nxt[3 * wid + 1] = cur[3 * wid + 1]
                    nxt[3 * wid + 2] = cur[3 * wid + 2]
                    continue
                avg_x = 0.0; avg_y = 0.0; avg_z = 0.0
                for neighbor in adj_a:
                    j = neighbor
                    avg_x += cur[3 * j]
                    avg_y += cur[3 * j + 1]
                    avg_z += cur[3 * j + 2]
                avg_x /= deg; avg_y /= deg; avg_z /= deg
                nxt[3 * wid]     = cur[3 * wid]     + factor * (avg_x - cur[3 * wid])
                nxt[3 * wid + 1] = cur[3 * wid + 1] + factor * (avg_y - cur[3 * wid + 1])
                nxt[3 * wid + 2] = cur[3 * wid + 2] + factor * (avg_z - cur[3 * wid + 2])
            cur, nxt = nxt, cur   # troca os buffers (double buffering)

    # --- espalha as posicoes suavizadas de volta pra cada SLOT original ---
    cdef np.ndarray[np.float32_t, ndim=1] new_vertices = np.empty(3 * n_slots, dtype=np.float32)
    for slot in range(n_slots):
        wid = slot_weld[slot]
        new_vertices[3 * slot]     = <np.float32_t> cur[3 * wid]
        new_vertices[3 * slot + 1] = <np.float32_t> cur[3 * wid + 1]
        new_vertices[3 * slot + 2] = <np.float32_t> cur[3 * wid + 2]

    # --- recalcula normais (por face, acumuladas por WELD ID -- nao por
    #     slot -- e normalizadas) a partir da geometria JA SUAVIZADA.
    #
    #     [BUG FIX] A primeira versao acumulava por SLOT original. Como a
    #     malha de entrada nao compartilha slot nenhum entre triangulos
    #     (cada triangulo tem seus proprios 3 slots -- ver nota no topo do
    #     arquivo), cada slot so' recebia a normal de UM triangulo, dando
    #     uma normal "flat" disfarcada de "por vertice". Isso fazia o modo
    #     smooth shading (que usa essa normal por vertice) ficar identico
    #     ao modo flat (que calcula a normal da face direto no shader,
    #     independente do que mandamos) -- exatamente o sintoma relatado.
    #     Agora acumula por WELD ID (a conectividade de verdade -- todos os
    #     triangulos que se tocam naquele ponto contribuem), calcula UMA
    #     normal suavizada por weld, e so' DEPOIS espalha essa mesma normal
    #     pra cada slot que colapsou naquele weld -- assim os slots que
    #     dividem um weld ficam com a MESMA normal (media de varias faces
    #     de verdade), permitindo o smooth shading funcionar. ---
    cdef np.ndarray[np.float64_t, ndim=1] weld_normal_accum = np.zeros(3 * n_welds, dtype=np.float64)
    cdef double ax, ay, az, bx, by, bz, cx0, cy0, cz0
    cdef double e1x, e1y, e1z, e2x, e2y, e2z, fnx, fny, fnz
    cdef Py_ssize_t ia, ib, ic, wa, wb, wc

    for i in range(n_tris):
        ia = indexes[3 * i]; ib = indexes[3 * i + 1]; ic = indexes[3 * i + 2]
        ax = new_vertices[3 * ia]; ay = new_vertices[3 * ia + 1]; az = new_vertices[3 * ia + 2]
        bx = new_vertices[3 * ib]; by = new_vertices[3 * ib + 1]; bz = new_vertices[3 * ib + 2]
        cx0 = new_vertices[3 * ic]; cy0 = new_vertices[3 * ic + 1]; cz0 = new_vertices[3 * ic + 2]
        e1x = bx - ax; e1y = by - ay; e1z = bz - az
        e2x = cx0 - ax; e2y = cy0 - ay; e2z = cz0 - az
        fnx = e1y * e2z - e1z * e2y
        fny = e1z * e2x - e1x * e2z
        fnz = e1x * e2y - e1y * e2x
        wa = slot_weld[ia]; wb = slot_weld[ib]; wc = slot_weld[ic]
        weld_normal_accum[3 * wa] += fnx; weld_normal_accum[3 * wa + 1] += fny; weld_normal_accum[3 * wa + 2] += fnz
        weld_normal_accum[3 * wb] += fnx; weld_normal_accum[3 * wb + 1] += fny; weld_normal_accum[3 * wb + 2] += fnz
        weld_normal_accum[3 * wc] += fnx; weld_normal_accum[3 * wc + 1] += fny; weld_normal_accum[3 * wc + 2] += fnz

    cdef np.ndarray[np.float64_t, ndim=1] weld_normal = np.empty(3 * n_welds, dtype=np.float64)
    cdef double nlen
    for wid in range(n_welds):
        nlen = (weld_normal_accum[3 * wid] ** 2 + weld_normal_accum[3 * wid + 1] ** 2
                + weld_normal_accum[3 * wid + 2] ** 2) ** 0.5
        if nlen > 1e-12:
            weld_normal[3 * wid]     = weld_normal_accum[3 * wid]     / nlen
            weld_normal[3 * wid + 1] = weld_normal_accum[3 * wid + 1] / nlen
            weld_normal[3 * wid + 2] = weld_normal_accum[3 * wid + 2] / nlen
        else:
            weld_normal[3 * wid]     = 0.0
            weld_normal[3 * wid + 1] = 0.0
            weld_normal[3 * wid + 2] = 1.0

    # Espalha a normal suavizada (por weld) de volta pra cada slot original
    # -- slots que compartilham um weld saem com a MESMA normal.
    cdef np.ndarray[np.float32_t, ndim=1] new_normals = np.empty(3 * n_slots, dtype=np.float32)
    for slot in range(n_slots):
        wid = slot_weld[slot]
        new_normals[3 * slot]     = <np.float32_t> weld_normal[3 * wid]
        new_normals[3 * slot + 1] = <np.float32_t> weld_normal[3 * wid + 1]
        new_normals[3 * slot + 2] = <np.float32_t> weld_normal[3 * wid + 2]

    return (new_vertices, new_normals)


cpdef list smooth_surface_trajectory(list surface_trajectory, int iterations = 10,
                                      double lambda_factor = 0.5, double mu_factor = -0.53,
                                      double weld_epsilon = 1e-4, list surf_names = None):
    """ Aplica taubin_smooth em TODOS os frames/lobulos de um
        vismol_object.surface_trajectory (a lista de dicts {surf_name:
        (vertices, colors, indexes, normals)} por frame -- essa e' a ORDEM
        da tupla usada la' (SurfaceRepresentation.draw_representation)).
        'colors' e 'indexes' saem inalterados; so' vertices/normals mudam.

        Returns:
            Uma NOVA lista de dicts (mesma estrutura), suavizada -- o
            surface_trajectory original NAO e' modificado.
    """
    cdef list new_trajectory = []
    cdef dict frame_data, new_frame_data
    cdef str surf_name
    cdef object vertices, colors, indexes, normals, v, n

    for frame_data in surface_trajectory:
        new_frame_data = {}
        for surf_name in frame_data.keys():
            if surf_names is not None and surf_name not in surf_names:
                new_frame_data[surf_name] = frame_data[surf_name]
                continue
            entry = frame_data[surf_name]
            # [BUG FIX] Ver o mesmo comentario em mesh_decimation.pyx:
            # superficies de MEP guardam 'mep_raw_potential_values' e
            # 'mep_raw_polygons' por frame, que NAO sao uma malha de 4
            # elementos -- desempacotar isso como (vertices, colors,
            # indexes, normals) falhava, quebrando a suavizacao pra
            # QUALQUER superficie de MEP. Agora so' processa entradas que
            # sao de fato uma malha; o resto passa direto, sem mudar.
            if not (isinstance(entry, (list, tuple)) and len(entry) == 4):
                new_frame_data[surf_name] = entry
                continue
            vertices, colors, indexes, normals = entry
            v, n = taubin_smooth(
                np.ascontiguousarray(vertices, dtype=np.float32).ravel(),
                np.ascontiguousarray(indexes,  dtype=np.uint32).ravel(),
                iterations, lambda_factor, mu_factor, weld_epsilon,
            )
            new_frame_data[surf_name] = (v, colors, indexes, n)
        new_trajectory.append(new_frame_data)

    return new_trajectory
