#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  EasyHybrid: Python interface for QM/MM and molecular simulations using pDynamo3
#  Module: Mesh decimation utilities for isosurface representations
#          (orbital / density / potential / MEP / external-cube surfaces
#          generated by marching cubes -- see surface_analysis_window.py).
#
#  Copyright 2022-2026 Fernando Bachega
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  Description:
#      Vertex Clustering mesh decimation. Groups nearby vertices into a
#      uniform spatial grid ("voxels"); every vertex that falls in the same
#      cell is replaced by a single representative vertex (the centroid of
#      their positions/normals/colors). Triangles that collapse to fewer
#      than 3 distinct vertices after this merge (i.e. zero area) are
#      discarded.
#
#      [BUG FIX / DATA LAYOUT] The first version of this file assumed
#      vertices/normals/colors were (N,3)-shaped numpy arrays. That is
#      WRONG for how surface_analysis_window.py actually builds a surface:
#      surface_parser()/surface_parser_mep() return FLAT 1-D arrays
#      (vertices_out = tri_verts.reshape(-1), etc. -- x0,y0,z0,x1,y1,z1,...
#      consecutively), with 'indexes' being one entry per VERTEX SLOT
#      (initially just np.arange(n_vertex_slots), since every triangle in
#      this codebase currently owns 3 unique, non-shared vertex slots --
#      no vertex welding happens anywhere before this module). Calling the
#      old (N,3)-typed Cython function with these flat 1-D arrays raised
#      "Buffer has wrong number of dimensions (expected 2, got 1)".
#
#      This version works directly on the REAL layout: flat 1-D
#      vertices/normals/colors, plus an 'indexes' array giving, for each
#      triangle corner, which vertex SLOT it refers to. A pleasant side
#      effect: since the input mesh has no vertex sharing at all (every
#      slot is unique even where triangles touch), clustering here also
#      performs the mesh's first-ever vertex welding, not just simplification.
#
#      Runs entirely on the already-extracted mesh, independent of how the
#      isosurface was produced -- no knowledge of grids, isovalues, or
#      molecular data at all.
#
import numpy as np
cimport numpy as np
cimport cython

#cython: boundscheck=False
#cython: wraparound=False
#cython: initializedcheck=False
#cython: cdivision=True

from libc.math cimport floor


@cython.boundscheck(False)
@cython.wraparound(False)
cpdef tuple vertex_clustering_decimate(np.ndarray[np.float32_t, ndim=1] vertices,
                                       np.ndarray[np.float32_t, ndim=1] normals,
                                       np.ndarray[np.float32_t, ndim=1] colors,
                                       np.ndarray[np.uint32_t,  ndim=1] indexes,
                                       double cell_size):
    """ Vertex Clustering decimation, for the FLAT mesh layout used
        throughout this codebase (see surface_parser()/surface_parser_mep()
        in surface_analysis_window.py).

        Parameters:
            vertices : (3*S,) float32 -- flat vertex positions, S = number
                       of vertex SLOTS (x0,y0,z0, x1,y1,z1, ...)
            normals  : (3*S,) float32 -- flat per-slot normals, same layout
            colors   : (C*S,) float32 -- flat per-slot colors, C is
                       whatever width the caller already uses (3 = RGB in
                       every surface type in this codebase today, but not
                       assumed/hardcoded here -- derived from S)
            indexes  : (K,) uint32 -- flat triangle index list (K = 3*T for
                       T triangles); indexes[k] is the vertex SLOT (0..S-1)
                       used by that triangle corner. Today this is always
                       np.arange(S) (no vertex sharing at all going in),
                       but this function does not assume that -- it reads
                       whichever slot each index actually points to.
            cell_size : float -- edge length of each grid cell, in the same
                       spatial units as 'vertices' (e.g. Angstrom). Every
                       vertex SLOT inside the same cell collapses into one
                       representative vertex. A good starting point is a
                       fraction (0.3-0.5x) of the marching-cubes grid
                       spacing used to generate the surface, so decimation
                       does not visibly change the isosurface's shape.

        Returns:
            (new_vertices, new_normals, new_colors, new_indexes) -- same
            flat layout/dtypes as the inputs. new_indexes is a REAL indexed
            mesh (vertices now genuinely shared across triangles, unlike
            the input).

        Degenerate/zero-area triangles (all 3 corners collapsed into fewer
        than 3 distinct clusters) are dropped, not left in the output.
    """
    cdef Py_ssize_t n_slots = vertices.shape[0] // 3
    cdef Py_ssize_t n_indexes = indexes.shape[0]
    cdef Py_ssize_t n_tris = n_indexes // 3
    cdef Py_ssize_t n_color_channels

    if n_slots == 0:
        n_color_channels = 0
    else:
        n_color_channels = colors.shape[0] // n_slots

    if cell_size <= 0.0:
        raise ValueError("cell_size deve ser positivo (recebido: {})".format(cell_size))
    if n_slots == 0 or n_tris == 0:
        return (vertices, normals, colors, indexes)

    cdef double min_x = vertices[0]
    cdef double min_y = vertices[1]
    cdef double min_z = vertices[2]
    cdef Py_ssize_t i, j, slot
    cdef float vx, vy, vz
    for i in range(1, n_slots):
        vx = vertices[3 * i]
        vy = vertices[3 * i + 1]
        vz = vertices[3 * i + 2]
        if vx < min_x: min_x = vx
        if vy < min_y: min_y = vy
        if vz < min_z: min_z = vz

    cdef dict cell_to_cluster = {}
    cdef np.ndarray[np.int64_t, ndim=1] slot_cluster = np.empty(n_slots, dtype=np.int64)
    cdef list sum_pos    = []
    cdef list sum_norm   = []
    cdef list sum_color  = []
    cdef list counts     = []
    cdef Py_ssize_t n_clusters = 0
    cdef Py_ssize_t ix, iy, iz
    cdef object key
    cdef Py_ssize_t cid

    for slot in range(n_slots):
        ix = <Py_ssize_t> floor((vertices[3 * slot]     - min_x) / cell_size)
        iy = <Py_ssize_t> floor((vertices[3 * slot + 1] - min_y) / cell_size)
        iz = <Py_ssize_t> floor((vertices[3 * slot + 2] - min_z) / cell_size)
        key = (ix, iy, iz)
        if key in cell_to_cluster:
            cid = cell_to_cluster[key]
            counts[cid] += 1
            sum_pos[cid][0]  += vertices[3 * slot]
            sum_pos[cid][1]  += vertices[3 * slot + 1]
            sum_pos[cid][2]  += vertices[3 * slot + 2]
            sum_norm[cid][0] += normals[3 * slot]
            sum_norm[cid][1] += normals[3 * slot + 1]
            sum_norm[cid][2] += normals[3 * slot + 2]
            for j in range(n_color_channels):
                sum_color[cid][j] += colors[n_color_channels * slot + j]
        else:
            cid = n_clusters
            cell_to_cluster[key] = cid
            counts.append(1)
            sum_pos.append([vertices[3 * slot], vertices[3 * slot + 1], vertices[3 * slot + 2]])
            sum_norm.append([normals[3 * slot], normals[3 * slot + 1], normals[3 * slot + 2]])
            sum_color.append([colors[n_color_channels * slot + j] for j in range(n_color_channels)])
            n_clusters += 1
        slot_cluster[slot] = cid

    cdef np.ndarray[np.float32_t, ndim=1] new_vertices = np.empty(3 * n_clusters, dtype=np.float32)
    cdef np.ndarray[np.float32_t, ndim=1] new_normals  = np.empty(3 * n_clusters, dtype=np.float32)
    cdef np.ndarray[np.float32_t, ndim=1] new_colors   = np.empty(n_color_channels * n_clusters, dtype=np.float32)
    cdef double nrm_len
    cdef double nx, ny, nz
    cdef Py_ssize_t cnt

    for cid in range(n_clusters):
        cnt = counts[cid]
        new_vertices[3 * cid]     = sum_pos[cid][0] / cnt
        new_vertices[3 * cid + 1] = sum_pos[cid][1] / cnt
        new_vertices[3 * cid + 2] = sum_pos[cid][2] / cnt
        nx = sum_norm[cid][0] / cnt
        ny = sum_norm[cid][1] / cnt
        nz = sum_norm[cid][2] / cnt
        nrm_len = (nx * nx + ny * ny + nz * nz) ** 0.5
        if nrm_len > 1e-12:
            new_normals[3 * cid]     = nx / nrm_len
            new_normals[3 * cid + 1] = ny / nrm_len
            new_normals[3 * cid + 2] = nz / nrm_len
        else:
            new_normals[3 * cid]     = 0.0
            new_normals[3 * cid + 1] = 0.0
            new_normals[3 * cid + 2] = 1.0
        for j in range(n_color_channels):
            new_colors[n_color_channels * cid + j] = sum_color[cid][j] / cnt

    cdef np.ndarray[np.uint32_t, ndim=1] tmp_indexes = np.empty(n_indexes, dtype=np.uint32)
    cdef Py_ssize_t out_count = 0
    cdef Py_ssize_t a, b, c

    for i in range(n_tris):
        a = slot_cluster[indexes[3 * i]]
        b = slot_cluster[indexes[3 * i + 1]]
        c = slot_cluster[indexes[3 * i + 2]]
        if a != b and b != c and a != c:
            tmp_indexes[out_count]     = <np.uint32_t> a
            tmp_indexes[out_count + 1] = <np.uint32_t> b
            tmp_indexes[out_count + 2] = <np.uint32_t> c
            out_count += 3

    cdef np.ndarray[np.uint32_t, ndim=1] new_indexes = tmp_indexes[:out_count].copy()

    return (new_vertices, new_normals, new_colors, new_indexes)


cpdef list decimate_surface_trajectory(list surface_trajectory, double cell_size,
                                        list surf_names = None):
    """ Aplica vertex_clustering_decimate em TODOS os frames/lobulos de um
        vismol_object.surface_trajectory (a lista de dicts {surf_name:
        (vertices, colors, indexes, normals)} por frame -- essa e' a ORDEM
        da tupla usada la' (SurfaceRepresentation.draw_representation),
        diferente da ordem de parametros/retorno de
        vertex_clustering_decimate acima; a reordenacao e' feita aqui
        dentro).

        Returns:
            Uma NOVA lista de dicts (mesma estrutura), decimada -- o
            surface_trajectory original NAO e' modificado.
    """
    cdef list new_trajectory = []
    cdef dict frame_data, new_frame_data
    cdef str surf_name
    cdef object vertices, colors, indexes, normals, v, n, c, idx

    for frame_data in surface_trajectory:
        new_frame_data = {}
        for surf_name in frame_data.keys():
            if surf_names is not None and surf_name not in surf_names:
                new_frame_data[surf_name] = frame_data[surf_name]
                continue
            vertices, colors, indexes, normals = frame_data[surf_name]
            v, n, c, idx = vertex_clustering_decimate(
                np.ascontiguousarray(vertices, dtype=np.float32).ravel(),
                np.ascontiguousarray(normals,  dtype=np.float32).ravel(),
                np.ascontiguousarray(colors,   dtype=np.float32).ravel(),
                np.ascontiguousarray(indexes,  dtype=np.uint32).ravel(),
                cell_size,
            )
            new_frame_data[surf_name] = (v, c, idx, n)
        new_trajectory.append(new_frame_data)

    return new_trajectory
